services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/messager

  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/messager

  queue-worker:
    build:
      context: docker/supervisor
      dockerfile: Dockerfile
    container_name: queue-worker
    volumes:
      - ./app:/var/www/messager
    depends_on:
      - php

  mysql:
    image: mysql:9.4
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:?error}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?error}
      MYSQL_PASSWORD: ${DB_PASSWORD:?error}
      MYSQL_USER: ${DB_USER:?error}
    volumes:
      - ./docker/mysql/db:/var/lib/mysql

  minio:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z-cpuv1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?error}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?error}
    volumes:
      - ./docker/minio/data:/data
    command: server /data --console-address ":9001"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    environment:
      SOKETI_DEBUG: '1'
      SOKETI_METRICS_SERVER_PORT: '9601'
      SOKETI_DEFAULT_APP_ID:  ${SOKETI_DEFAULT_APP_ID:?error}
      SOKETI_DEFAULT_APP_KEY:  ${SOKETI_DEFAULT_APP_KEY:?error}
      SOKETI_DEFAULT_APP_SECRET: ${SOKETI_DEFAULT_APP_SECRET:?error}
      SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES: "true"

      SOKETI_DEFAULT_APP_PING_INTERVAL: '25000'   # отправка пинга каждые 25 секунд
      SOKETI_DEFAULT_APP_PING_TIMEOUT: '60000'    # ожидание пинга 60 секунд
      SOKETI_DEFAULT_APP_CLIENT_TIMEOUT: '600000' # 10 минут без активности1
    ports:
      - '6001:6001'
      - '9601:9601'